/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Clients: () => import('#controllers/clients_controller'),
  InvoiceSettings: () => import('#controllers/invoice_settings_controller'),
  Invoices: () => import('#controllers/invoices_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
}
