/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ClientSchema extends BaseModel {
  static $columns = ['address', 'city', 'country', 'createdAt', 'email', 'id', 'name', 'phone', 'updatedAt', 'zip'] as const
  $columns = ClientSchema.$columns
  @column()
  declare address: string
  @column()
  declare city: string
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare zip: string
}

export class InvoiceItemSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'invoiceId', 'price', 'quantity', 'sortOrder', 'total', 'updatedAt'] as const
  $columns = InvoiceItemSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare invoiceId: number | null
  @column()
  declare price: number
  @column()
  declare quantity: number
  @column()
  declare sortOrder: number
  @column()
  declare total: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class InvoiceSettingSchema extends BaseModel {
  static $columns = ['addressLine1', 'addressLine2', 'bankAccountName', 'bankName', 'bic', 'businessName', 'city', 'country', 'createdAt', 'defaultPaymentDueDays', 'email', 'gisaNumber', 'iban', 'id', 'phone', 'smallBusinessText', 'taxNumber', 'updatedAt', 'zip'] as const
  $columns = InvoiceSettingSchema.$columns
  @column()
  declare addressLine1: string
  @column()
  declare addressLine2: string | null
  @column()
  declare bankAccountName: string
  @column()
  declare bankName: string
  @column()
  declare bic: string
  @column()
  declare businessName: string
  @column()
  declare city: string
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare defaultPaymentDueDays: number
  @column()
  declare email: string
  @column()
  declare gisaNumber: string | null
  @column()
  declare iban: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phone: string | null
  @column()
  declare smallBusinessText: string
  @column()
  declare taxNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare zip: string
}

export class InvoiceSchema extends BaseModel {
  static $columns = ['clientId', 'createdAt', 'id', 'issuedAt', 'number', 'paymentMethod', 'pdfPath', 'status', 'total', 'updatedAt', 'year'] as const
  $columns = InvoiceSchema.$columns
  @column()
  declare clientId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare issuedAt: DateTime | null
  @column()
  declare number: number
  @column()
  declare paymentMethod: string
  @column()
  declare pdfPath: string | null
  @column()
  declare status: number | null
  @column()
  declare total: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare year: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
